FROM debian

ADD debian.list /etc/apt/sources.list.d/


RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p zhets.com/img && \
    chmod -R 754 /var/www/zhets.com/ && \
    useradd zhetsynya  && groupadd Boldyk && usermod -a -G Boldyk zhetsynya  && \
    chown -R zhetsynya :Boldyk /var/www/zhets.com && \
    sed -i 's$/var/www/html$/var/www/zhets.com$g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user zhetsynya /g' /etc/nginx/nginx.conf
	
ADD index.html /var/www/zhets.com/
ADD img.jpg /var/www/zhets.com/img/
CMD ["nginx", "-g", "daemon off;"]